# Generated by Django 5.2.3 on 2025-06-20 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('url', models.URLField()),
                ('date', models.DateField()),
                ('image', models.URLField(blank=True)),
            ],
        ),
    ]
